version: '3.9'
services:

  postgres:
    image: postgres
    restart: always
    hostname: postgres-host
    container_name: postgres
    shm_size: 4gb
    command: postgres -c wal_level=logical
    environment:
      POSTGRES_PASSWORD: secret
      POSTGRES_USER: postgres
      POSTGRES_DB: builder
    ports:
      - 5432:5432
    volumes:
      - ./data:/var/lib/postgresql/data
    networks:
        - debezium

  debezium-server:
    image: debezium/server
    container_name: debezium-server
    volumes:
      - ~/.aws:/home/jboss/.aws:ro
      - ./conf:/debezium/conf
      - ./debezium/data:/debezium/data
    depends_on:
      - postgres
    networks:
      - debezium
networks:
  debezium:
    driver: bridge